### ISSUE TITLE
AST parsing throws exception

### ISSUE THREAD

**Issue by liupibm** [QISKit/qiskit-sdk-py#213] opened 2017-12-21 20:46 UTC
## AST parsing crashes on the following file:
https://github.com/QISKit/openqasm/blob/master/examples/ibmqx2/qe_qft_4.qasm

## code for reproducing the crash:
from qiskit import qasm, unroll
basis_gates = "id,x,y,z,h,s,sdg,cx,t,tdg,u1,u2,u3,cy,cz,ccx,cu1,cu3".split(",")
ast = qasm.Qasm(filename=qasm_file).parse() # Node (AST)

## Stack trace:
> ANALYZING /Users/liup/quantum/qiskit-pull-requests/qiskit/tools/sympy_executor/testcases/test.qasm
Traceback (most recent call last):
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/tools/sympy_executor/sympy_executor.py", line 88, in <module>
    ast = buildAST(qasm_file)
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/tools/sympy_executor/sympy_executor.py", line 60, in buildAST
    ast = qasm.Qasm(filename=qasm_file).parse()  # Node (AST)
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/qasm/_qasm.py", line 58, in parse
    return qasm_p.parse(self._data)
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/qasm/_qasmparser.py", line 1098, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/qasm/_qasmparser.py", line 634, in p_unitary_op_2
    self.verify_as_gate(program[1], program[2])
  File "/Users/liup/quantum/qiskit-pull-requests/qiskit/qasm/_qasmparser.py", line 141, in verify_as_gate
    str(obj.line), 'file', obj.file)
qiskit.qasm._qasmerror.QasmError: "Gate or opaque call to 'ccx' uses 1 qubits but is declared for 3 qubits line 87 file /Users/liup/quantum/qiskit-pull-requests/qiskit/tools/sympy_executor/testcases/test.qasm"
Error near line 87 Column 24

**Comment by awcross1** [comment] 2017-12-21 21:52
Hi @liupibm, I can't reproduce this error. I see your file name is called "test.qasm". Does your QASM source file differ from the one in the openqasm repository?

**Comment by liupibm** [comment] 2017-12-21 22:18
hi @awcross1 sorry for the confusion, 
please update filename= qasm_file  properly to refer to qe_qft_4.qasm.

**Comment by awcross1** [comment] 2017-12-22 04:04
@liupibm Thanks but I had added that line when I tried to reproduce the error the first time. The file qe_qft_4.qasm parses correctly for me. In your output, the QasmError exception refers to /Users/liup/quantum/qiskit-pull-requests/qiskit/tools/sympy_executor/testcases/test.qasm, which suggests that you are parsing a different file than qe_qft_4.qasm, unless you changed its name to test.qasm. The error also suggests there might be a line in test.qasm like "ccx q[0];" which is incompatible with the definition of ccx. Let me know if something like this is going on, since I can't seem to reproduce the error.

**Comment by liupibm** [comment] 2017-12-22 04:14
[testcase.zip](https://github.com/QISKit/qiskit-sdk-py/files/1581400/testcase.zip)
@awcross1 

## reproduction:
please download testcase.zip and unzip it,
then run it: python3 test.py

## It will lead to:
Error near line 87 Column 24
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    ast = qasm.Qasm(filename='test.qasm').parse() # Node (AST)
  File "/usr/local/lib/python3.6/site-packages/qiskit-0.4.0-py3.6.egg/qiskit/qasm/_qasm.py", line 58, in parse
    return qasm_p.parse(self._data)
  File "/usr/local/lib/python3.6/site-packages/qiskit-0.4.0-py3.6.egg/qiskit/qasm/_qasmparser.py", line 1074, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/lib/python3.6/site-packages/qiskit-0.4.0-py3.6.egg/qiskit/qasm/_qasmparser.py", line 639, in p_unitary_op_2
    self.verify_as_gate(program[1], program[2])
  File "/usr/local/lib/python3.6/site-packages/qiskit-0.4.0-py3.6.egg/qiskit/qasm/_qasmparser.py", line 146, in verify_as_gate
    str(obj.line), 'file', obj.file)
qiskit.qasm._qasmerror.QasmError: "Gate or opaque call to 'ccx' uses 1 qubits but is declared for 3 qubits line 87 file test.qasm"

**Comment by liupibm** [comment] 2017-12-22 13:18
@awcross1 
Please close this issue. 

I found an error in test.qasm.
ccx q[0] q[1], q[2];
should be 
ccx q[0], q[1], q[2];

Thanks

**Comment by awcross1** [comment] 2017-12-22 14:22
Ok @liupibm no problem, I'll close the issue.

**Closed** 2017-12-22 14:23 UTC
