### ISSUE TITLE
Error in trying to run the software developer challenge test.

### ISSUE THREAD

**Issue by vtomole** [QISKit/qiskit-sdk-py#253] opened 2018-01-16 00:07 UTC
Summary: I Can't test the compiler function in the software developer challenge because of a json error.

## Expected Behavior
The program should tell me how much faster and better my compiler is compared to the QISkit reference compiler.

## Current Behavior
This is what I get instead 

```
vtomole@vtomole:~/noy/challenge$ python test.py
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
 File "/home/vtomole/anaconda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
   r = call_item.fn(*call_item.args, **call_item.kwargs)
 File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/_jobprocessor.py", line 54, in run_backend
   return backend.run(q_job)
 File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 83, in run
   result = run(qobj, self._configuration['exe'])
 File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 160, in run
   cresult = json.loads(cout.decode())
 File "/home/vtomole/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
   return _default_decoder.decode(s)
 File "/home/vtomole/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/home/vtomole/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "test.py", line 33, in <module>
   result = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)
 File "/home/vtomole/noy/challenge/challenge_evaluation.py", line 271, in evaluate
   data_original = res_original.get_data(name)
 File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/_result.py", line 204, in get_data
   raise exception
 File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/_jobprocessor.py", line 99, in _job_done_callback
   result = future.result()
 File "/home/vtomole/anaconda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
   return self.__get_result()
 File "/home/vtomole/anaconda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
   raise self._exception
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

## Steps to Reproduce (for bugs)
Run a script that contains:

```
# Import your solution function
from challenge_submission import compiler_function

# Import submission evaluation and scoring functions
from challenge_evaluation import evaluate, score

# Possibly useful other helper function
from challenge_evaluation import qasm_to_dag_circuit, load_coupling, get_layout

# Select the simulation backend to calculate the quantum states resulting from the circuits
# On Windows platform the C++ Simulator is not yet available with pip install
backend = 'local_qiskit_simulator'


ex_nr = 1
test_circuit_filenames = {}


for i in range(ex_nr):
    test_circuit_filenames['circuits/random%d_n5_d5.qasm' % i] = get_layout(5)
for i in range(ex_nr):
    test_circuit_filenames['circuits/random%d_n16_d16.qasm' % i] = get_layout(16)
for i in range(ex_nr):
    test_circuit_filenames['circuits/random%d_n20_d20.qasm' % i] = get_layout(20)

    test_circuits = {}

for filename, cmap in test_circuit_filenames.items():
    with open(filename, 'r') as infile:
        qasm = infile.read()        
        test_circuits[filename] = {"qasm": qasm, "coupling_map": cmap}

result = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)

myres = score(compiler_function, backend = backend)
print("Your compiler scored %6.5f x better \
and was %6.5f x faster than the QISKit reference compiler." % myres)
```

## Context
This issue is preventing me from testing the performance of my implementation of the compiler function.

## Your Environment

* Version used: qiskit version: 0.4.5
* Environment name and version (e.g. Python 3.6.1): Python 3.6.2 :: Anaconda custom (64-bit)

* Operating System and version: Ubuntu 16.04

**Comment by atilag** [comment] 2018-01-19 12:15
I tried to reproduce the error by executing the test file, but I couldn't because the `score()` function takes too long to finish on my computer, anyway the `evaluate()` worked fined.
Do you always get this very same error every time??

**Comment by vtomole** [comment] 2018-01-19 19:21
>Do you always get this very same error every time?
Yes. From HowTo-QISKit_Developer_Challenge.ipynb

```
result = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)
--------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/vtomole/anaconda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/_jobprocessor.py", line 54, in run_backend
    return backend.run(q_job)
  File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 83, in run
    result = run(qobj, self._configuration['exe'])
  File "/home/vtomole/anaconda/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 160, in run
    cresult = json.loads(cout.decode())
  File "/home/vtomole/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/vtomole/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vtomole/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-839f452fcc7a> in <module>()
----> 1 result = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)

~/noy/challenge/challenge_evaluation.py in evaluate(compiler_function, test_circuits, verbose, backend)
    269         for name in results.keys():
    270             # handle errors here
--> 271             data_original = res_original.get_data(name)
    272             if test_circuits[name]["dag_optimized"]is not None:
    273                 data_optimized = res_optimized.get_data(name)

~/anaconda/lib/python3.6/site-packages/qiskit/_result.py in get_data(self, name)
    202             exception = self._result['result']
    203             if isinstance(exception, BaseException):
--> 204                 raise exception
    205             else:
    206                 raise QISKitError(str(exception))

~/anaconda/lib/python3.6/site-packages/qiskit/_jobprocessor.py in _job_done_callback(self, future)
     97     def _job_done_callback(self, future):
     98         try:
---> 99             result = future.result()
    100         except Exception as ex:  # pylint: disable=broad-except
    101             result = Result({'job_id': '0', 'status': 'ERROR',

~/anaconda/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    396                 raise CancelledError()
    397             elif self._state == FINISHED:
--> 398                 return self.__get_result()
    399 
    400             self._condition.wait(timeout)

~/anaconda/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    355     def __get_result(self):
    356         if self._exception:
--> 357             raise self._exception
    358         else:
    359             return self._result

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by itoko** [comment] 2018-01-24 05:07
Hi, @vtomole. Could you try `backend = 'local_qasm_simulator'` instead of `backend = 'local_qiskit_simulator'` as workaround? 
(Note that local_qasm_simulator is slower than local_qiskit_simulator, though)
I guess the error implies that _qiskit_cpp_simulator.py failed to handle stdout string from qiskit_simulator.exe with some reason (and try to decode null string -> error).

**Comment by vtomole** [comment] 2018-01-26 18:18
New error from running ```HowTo-QISKit_Developer_Challenge.ipynb```

```
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    myres = score(compiler_function, backend = backend)
  File "/home/vtomole/noy/challenge/challenge_evaluation.py", line 74, in score
    with open(filename, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'circuits/random9_n5_d5.qasm'


```

**Comment by ajavadia** [comment] 2018-02-01 18:52
The missing file in the last comment is restored (download the latest version of the developer challenge).
I have not been able to reproduce the original issue though.

**Comment by vtomole** [comment] 2018-02-04 17:59
I ran  `HowTo-QISKit_Developer_Challenge.ipynb` again on 8 GB RAM. Specifically: https://github.com/vtomole/qchackers/blob/master/software/qiskit/test.py. I got

```
vtomole@vtomole:~/qchackers/software/qiskit/challenge_24_1_2018$ python test.py 
['ibmqx5',
 'ibmqx4',
 'ibmqx_hpc_qasm_simulator',
 'ibmqx2',
 'ibmqx_qasm_simulator',
 'local_qasm_simulator',
 'local_clifford_simulator',
 'local_qiskit_simulator',
 'local_unitary_simulator']
An error occurred in the user compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
An error occurred in the QISKit compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    myres = score(compiler_function, backend = backend)
  File "/home/vtomole/qchackers/software/qiskit/challenge_24_1_2018/challenge_evaluation.py", line 80, in score
    res = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)
  File "/home/vtomole/qchackers/software/qiskit/challenge_24_1_2018/challenge_evaluation.py", line 226, in evaluate
    res_original = qp.run(qobj_original, timeout=GLOBAL_TIMEOUT)
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/_quantumprogram.py", line 1233, in run
    self.wait_for_results(timeout)
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/_quantumprogram.py", line 1341, in wait_for_results
    'seconds.'.format(timeout))
qiskit._qiskiterror.QISKitError: 'Error waiting for Job results: Timeout after 10800 seconds.'
```

It looks like my machine is not powerful enough to test these circuits. What do you recommend i do?

**Comment by ajavadia** [comment] 2018-02-04 18:37
@vtomole, are you running on Windows? I'm wondering if that's why you get errors from the faster `local_qiskit_simulator`.
Your test script shows you are using the `local_qasm_simulator`, which is a slow simulator written in Python. So I'm not not surprised that the simulations do not finish in a reasonable time. You may use this slower backend to test your solution on the smaller circuits for now (5 and perhaps 16 qubits). But for the 20 qubits you really need the `local_qiskit_simulator`, implemented in C++.
@atilag is working on a Windows solution to this I think (#265).

**Comment by vtomole** [comment] 2018-02-04 19:11
@ajavadia  I'm on Ubuntu 16.04. Re-running with ```local_qasm_simulator``` now.  I'll update you on the results.

**Comment by ajavadia** [comment] 2018-02-04 20:21
@vtomole Your hardware should not be a problem. The largest circuits in the tests have 20 qubits, so the quantum state vector easily fits inside memory (~16MB). The problem is just that `local_qasm_simulator` is Python-based and slow. You will have to run the large circuits using a c++ simulator. QISKit's native c++ simulator is `local_qiskit_simulator`.

Here is another solution: 
You can run your circuits using Project Q's simulator. This is another fast c++ simulator. Here are the steps:
1. First install projectq: `python -m pip install --user projectq`
2. If you successfully got projectq, including its simulator, then you should be able to see it in QISKit's available backends by running this in Python:
```
import Qconfig
from qiskit import QuantumProgram
qp = QuantumProgram()
qp.set_api(Qconfig.APItoken, Qconfig.config['url'])
qp.available_backends()
```
Verify that you have `local_projectq_simulator`.
3. Change `backend=local_projectq_simulator`
4. In challenge_evaluation.py, wherever you see `seed=None`, change it to `seed=1`.
5. In challenge_evaluation.py, change `GLOBAL_TIMEOUT = 3600` to `GLOBAL_TIMEOUT = 7200`.
6. Run the score function again.

Let me know if this works.

**Comment by vtomole** [comment] 2018-02-05 16:10
```
vtomole@vtomole:~/qchackers/software/challenge_24_1_2018$ python test.py 
An error occurred in the user compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
An error occurred in the QISKit compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/vtomole/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/_jobprocessor.py", line 54, in run_backend
    return backend.run(q_job)
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 84, in run
    result = run(qobj, self._configuration['exe'])
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/backends/_qiskit_cpp_simulator.py", line 161, in run
    cresult = json.loads(cout.decode())
  File "/home/vtomole/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/vtomole/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/vtomole/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    myres = score(compiler_function, backend = backend)
  File "/home/vtomole/qchackers/software/challenge_24_1_2018/challenge_evaluation.py", line 80, in score
    res = evaluate(compiler_function, test_circuits, verbose=True, backend = backend)
  File "/home/vtomole/qchackers/software/challenge_24_1_2018/challenge_evaluation.py", line 299, in evaluate
    data_original = res_original.get_data(name)
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/_result.py", line 204, in get_data
    raise exception
  File "/home/vtomole/anaconda3/lib/python3.6/site-packages/qiskit/_jobprocessor.py", line 99, in _job_done_callback
    result = future.result()
  File "/home/vtomole/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/vtomole/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
test.py: https://github.com/vtomole/qchackers/blob/master/software/qiskit/challenge_24_1_2018/test.py

**Comment by ajavadia** [comment] 2018-02-05 17:54
@vtomole this is the original issue you reported, with `local_qiskit_simulator`. Did you try the Project Q simulator that I mentioned above?

**Comment by vtomole** [comment] 2018-02-06 04:16
I installed projectq, but the back-end is not being detected.

```
vtomole@vtomole:~/qchackers/software/qiskit/challenge_24_1_2018$ python -m pip install --user projectq
Requirement already satisfied: projectq in /home/vtomole/.local/lib/python3.6/site-packages
Requirement already satisfied: numpy in /home/vtomole/anaconda3/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: future in /home/vtomole/.local/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: pytest>=3.1 in /home/vtomole/.local/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: pybind11!=2.2.0,>=1.7 in /home/vtomole/.local/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: requests in /home/vtomole/anaconda3/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: scipy in /home/vtomole/anaconda3/lib/python3.6/site-packages (from projectq)
Requirement already satisfied: py>=1.5.0 in /home/vtomole/.local/lib/python3.6/site-packages (from pytest>=3.1->projectq)
Requirement already satisfied: pluggy<0.7,>=0.5 in /home/vtomole/.local/lib/python3.6/site-packages (from pytest>=3.1->projectq)
Requirement already satisfied: six>=1.10.0 in /home/vtomole/anaconda3/lib/python3.6/site-packages (from pytest>=3.1->projectq)
Requirement already satisfied: attrs>=17.2.0 in /home/vtomole/.local/lib/python3.6/site-packages (from pytest>=3.1->projectq)
Requirement already satisfied: setuptools in /home/vtomole/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from pytest>=3.1->projectq)
vtomole@vtomole:~/qchackers/software/qiskit/challenge_24_1_2018$ python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Qconfig
>>> from qiskit import QuantumProgram
>>> qp = QuantumProgram()
>>> qp.set_api(Qconfig.APItoken, Qconfig.config['url'])
>>> qp.available_backends()
['ibmqx5', 'ibmqx4', 'ibmqx_hpc_qasm_simulator', 'ibmqx2', 'ibmqx_qasm_simulator', 'local_qasm_simulator', 'local_clifford_simulator', 'local_qiskit_simulator', 'local_unitary_simulator']
```

**Comment by vtomole** [comment] 2018-02-06 16:57
@ajavadia I solved that problem here: https://github.com/ProjectQ-Framework/ProjectQ/issues/202#issuecomment-363472926.

It runs on ```local_projectq_simulator``` now. 
```
vtomole@vtomole:~/qchackers/software/qiskit/challenge_24_1_2018$ python test.py 
An error occurred in the user compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
An error occurred in the QISKit compiler while running circuits/random3_n20_d20.qasm on {0: [5, 1], 2: [3], 7: [6], 8: [13, 9, 7], 11: [10], 12: [17, 7, 13, 11], 13: [14], 15: [16], 18: [13, 19, 17], 6: [1], 3: [8], 9: [14, 4], 16: [11], 19: [14]}.
Your compiler scored 0.96774 x better and was 0.96675 x faster than the QISKit reference compiler.
```
Thank you.

**Comment by ajavadia** [comment] 2018-02-06 20:32
@vtomole, great, i'm glad it worked. 
that is a numerical precision issue that has been observed on some systems with some input circuits. it is being tracked elsewhere (#158). it is specific to the current compiler implementation, so the improved compiler that you submit does not have to encounter this error.
i will close this issue but feel free to reopen if you run into other problems.

**Closed** 2018-02-06 20:32 UTC
